baseURL = '/'
languageCode = 'en-us'
title = 'Beehaw Docs'

contentDir = "content"
enableEmoji = true
enableGitInfo = true

[build]
  noJSConfigInAssets = true

[params]
  [params.docs]
    darkMode = true
    themeColor = "yellow"
    prism = false
    breadcrumbs = false
    sidebarIcons = true
    titleIcon = true
    ghrepo = "github.com/beehaw-org/beehaw-org.github.io"
    editPage = true
    lastMod = true

[module]
  replacements = "github.com/colinwilson/lotusdocs -> lotusdocs"
  [[module.imports]]
      path = "github.com/colinwilson/lotusdocs"
      disable = false
  [[module.imports]]
      path = "github.com/gohugoio/hugo-mod-bootstrap-scss/v5"
      disable = false
